<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PaintTranslator.BlendTests</RootNamespace>
    <AssemblyName>PaintTranslator.BlendTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaintTranslator.csproj" />
  </ItemGroup>

</Project>
