using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using PaintTranslator.Pigments;

namespace IngestSpectra
{
    /// <summary>
    /// Entry point for the offline coefficient ingest. Writes the embedded resource the
    /// application reads, plus a human-readable manifest that makes a bad ingest visible
    /// in review even though the resource itself is binary.
    /// </summary>
    public static class Program
    {
        /// <summary>
        /// Runs the ingest.
        /// </summary>
        /// <param name="args">Optional single argument: the repository root. Defaults to
        /// three directories above the working directory.</param>
        public static void Main(string[] args)
        {
            string root = args.Length > 0 ? args[0] : Path.GetFullPath(Path.Combine("..", "..", ".."));
            string pigmentsDirectory = Path.Combine(root, "Pigments");
            Directory.CreateDirectory(pigmentsDirectory);

            var paints = new List<PigmentCoefficients>();
            foreach (ExtractedPigment extracted in BernsSource.Extract())
            {
                paints.Add(new PigmentCoefficients(
                    extracted.Name,
                    extracted.ColourIndex,
                    PigmentProvenance.TwoConstantMeasured,
                    extracted.Absorption,
                    extracted.Scattering));
            }

            string spectraPath = Path.Combine(
                AppContext.BaseDirectory, "..", "..", "..", "data", "GoldenSpectra.zip");
            spectraPath = Path.GetFullPath(spectraPath);

            if (File.Exists(spectraPath))
            {
                var measuredNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                foreach (PigmentCoefficients paint in paints)
                {
                    measuredNames.Add(paint.Name);
                }

                paints.AddRange(GoldenSpectraSource.Derive(spectraPath, measuredNames));
                Console.WriteLine($"Added {paints.Count - measuredNames.Count} reflectance-derived paints.");
            }
            else
            {
                Console.WriteLine($"No GoldenSpectra.zip at {spectraPath}; writing the measured tier only.");
            }

            string resourcePath = Path.Combine(pigmentsDirectory, "PigmentData.bin");
            using (FileStream stream = File.Create(resourcePath))
            {
                PigmentData.Write(stream, paints);
            }

            WriteManifest(Path.Combine(pigmentsDirectory, "pigments.manifest.txt"), paints);

            Console.WriteLine($"Wrote {paints.Count} paints to {resourcePath} " +
                $"({new FileInfo(resourcePath).Length} bytes).");
        }

        /// <summary>
        /// Writes the reviewable summary that stands in for a readable diff of the
        /// binary resource.
        /// </summary>
        /// <param name="path">The manifest path.</param>
        /// <param name="paints">The paints written to the resource.</param>
        private static void WriteManifest(string path, IReadOnlyList<PigmentCoefficients> paints)
        {
            var manifest = new StringBuilder();
            manifest.AppendLine("# Generated by Tools/IngestSpectra. Do not edit by hand.");
            manifest.AppendLine("# name | colour index | provenance | L* | a* | b*");

            var reflectance = new double[SpectralBands.Count];
            foreach (PigmentCoefficients paint in paints)
            {
                KubelkaMunk.Mix(new[] { paint }, new[] { 1.0 }, reflectance);
                SpectralRenderer.ToLab(reflectance, out double lightness, out double aStar, out double bStar);

                manifest.AppendLine(string.Format(
                    CultureInfo.InvariantCulture,
                    "{0} | {1} | {2} | {3:F2} | {4:F2} | {5:F2}",
                    paint.Name,
                    paint.ColourIndex,
                    paint.Provenance,
                    lightness,
                    aStar,
                    bStar));
            }

            File.WriteAllText(path, manifest.ToString());
        }
    }
}
